// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title MockVerifier
 * @notice A mock Groth16 verifier that always returns true.
 * @dev Used for unit testing when the real ZKP circuit is not compiled.
 *      The real Verifier.sol is auto-generated by snarkjs during setup.
 */
contract MockVerifier {
    function verifyProof(
        uint256[2] calldata /* _pA */,
        uint256[2][2] calldata /* _pB */,
        uint256[2] calldata /* _pC */,
        uint256[3] calldata /* _pubSignals */
    ) external pure returns (bool) {
        return true;
    }
}
