/**
 * Deployment Configuration
 * Auto-loaded from deployment.json generated by the deploy script
 */

export const DEPLOYMENT = {
  network: "localhost",
  chainId: 1337,
  rpcUrl: "http://127.0.0.1:8545",
  apiUrl: "http://localhost:3001",
  contracts: {
    Verifier: "0x70e0bA845a1A0F2DA3359C97E0285013525FFC49",
    VoterEligibility: "0x4826533B4897376654Bb4d4AD88B7faFD0C98528",
    Voting: "0x99bbA657f2BbC93c02D617f8bA121cB8Fc104Acf",
    SmartAccountFactory: "0x0E801D84Fa97b50751Dbf25036d067dCf18858bF",
    VotingPaymaster: "0x8f86403A4DE0BB5791fa46B8e795C547942fE4Cf",
  },
  election: {
    id: 1,
    title: "2025 SUG Presidential Election",
    candidates: [
      { id: 1, name: "Adewale Johnson", party: "Progressive Students Alliance" },
      { id: 2, name: "Chioma Okafor", party: "Students United Front" },
      { id: 3, name: "Emeka Nwosu", party: "Academic Excellence Movement" },
    ],
  },
};

export const VOTING_ABI = [
  "function endElection() external",
  "function initializeElection(uint256 _electionId, uint256 _startTime, uint256 _endTime) external",
  "function addCandidate(uint256 _candidateId, string calldata _name, string calldata _party) external",
  "function castVote(bytes32 _didHash, uint256 _candidateId) external",
  "function electionActive() view returns (bool)",
  "function electionEnd() view returns (uint256)",
  "function electionStart() view returns (uint256)",
  "function electionId() view returns (uint256)",
  "function getResults(uint256 _electionId) view returns (uint256[] ids, string[] names, string[] parties, uint256[] voteCounts)",
  "function getWinner(uint256 _electionId) view returns (uint256 winnerId, string winnerName, uint256 winnerVotes)",
  "function hasVoterVoted(uint256 _electionId, bytes32 _didHash) view returns (bool)",
  "function totalVotesCast(uint256) view returns (uint256)",
  "function candidateCount(uint256) view returns (uint256)",
  "event VoteCast(uint256 indexed electionId, bytes32 indexed didHash, uint256 indexed candidateId)",
  "event ElectionEnded(uint256 indexed electionId, uint256 totalVotes)",
];

export const ELIGIBILITY_ABI = [
  "function verifyAndRegister(uint256[2] calldata _pA, uint256[2][2] calldata _pB, uint256[2] calldata _pC, uint256[3] calldata _pubSignals, bytes32 _didHash) external",
  "function createElection(uint256 _electionId) external",
  "function addEnrollmentCommitments(bytes32[] calldata _commitments) external",
  "function isEligible(uint256 _electionId, bytes32 _didHash) view returns (bool)",
  "function eligibleVoterCount() view returns (uint256)",
  "function currentElectionId() view returns (uint256)",
  "event VoterVerified(bytes32 indexed didHash, bytes32 indexed nullifierHash)",
];
