// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IGroth16Verifier
 * @notice Interface for the auto-generated Groth16 verifier from snarkjs
 */
interface IGroth16Verifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[4] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title VoterEligibility
 * @author Katoh Thesis Project
 * @notice Verifies student enrollment eligibility using zk-SNARK proofs and
 *         manages the set of eligible voters for an election.
 * @dev This contract:
 *   - Accepts a Groth16 proof proving a student holds valid enrollment data
 *     matching a known commitment, without revealing personal academic records.
 *   - Uses a nullifier hash to prevent a student from registering twice for the
 *     same election.
 *   - Maintains a registry of eligible DIDs that the Voting contract references.
 */
contract VoterEligibility {
    // -------------------------------------------------------
    // State
    // -------------------------------------------------------

    /// @notice The admin (university) who manages elections and enrollment commitments
    address public admin;

    /// @notice The on-chain Groth16 verifier contract (auto-generated by snarkjs)
    IGroth16Verifier public verifier;

    /// @notice The current election identifier
    uint256 public currentElectionId;

    /// @notice Whether an enrollment commitment is registered (set by admin during enrollment)
    mapping(bytes32 => bool) public enrollmentCommitments;

    /// @notice Whether a nullifier hash has been used (prevents double registration)
    mapping(bytes32 => bool) public usedNullifiers;

    /// @notice Whether a DID is marked as eligible for a specific election
    mapping(uint256 => mapping(bytes32 => bool)) public eligibleVoters;

    /// @notice Total number of eligible voters registered for the current election
    uint256 public eligibleVoterCount;

    // -------------------------------------------------------
    // Events
    // -------------------------------------------------------

    event EnrollmentCommitmentAdded(bytes32 indexed commitment);
    event EnrollmentCommitmentRevoked(bytes32 indexed commitment);
    event VoterVerified(bytes32 indexed didHash, bytes32 indexed nullifierHash);
    event ElectionCreated(uint256 indexed electionId);

    // -------------------------------------------------------
    // Modifiers
    // -------------------------------------------------------

    modifier onlyAdmin() {
        require(msg.sender == admin, "VoterEligibility: caller is not admin");
        _;
    }

    // -------------------------------------------------------
    // Constructor
    // -------------------------------------------------------

    /**
     * @param _verifier Address of the deployed Groth16 verifier contract
     */
    constructor(address _verifier) {
        admin = msg.sender;
        verifier = IGroth16Verifier(_verifier);
    }

    // -------------------------------------------------------
    // Admin Functions
    // -------------------------------------------------------

    /**
     * @notice Start a new election. Resets eligibility state.
     * @param _electionId Unique identifier for the election
     */
    function createElection(uint256 _electionId) external onlyAdmin {
        require(_electionId > 0, "VoterEligibility: invalid election ID");
        currentElectionId = _electionId;
        eligibleVoterCount = 0;
        emit ElectionCreated(_electionId);
    }

    /**
     * @notice Register enrollment commitments (batch). Called during student enrollment.
     * @dev The commitment is Poseidon(matricNumber, departmentId, enrollmentSecret)
     * @param _commitments Array of enrollment commitments to register
     */
    function addEnrollmentCommitments(bytes32[] calldata _commitments) external onlyAdmin {
        for (uint256 i = 0; i < _commitments.length; i++) {
            enrollmentCommitments[_commitments[i]] = true;
            emit EnrollmentCommitmentAdded(_commitments[i]);
        }
    }

    /**
     * @notice Revoke an enrollment commitment (e.g., student expelled)
     * @param _commitment The commitment to revoke
     */
    function revokeEnrollmentCommitment(bytes32 _commitment) external onlyAdmin {
        enrollmentCommitments[_commitment] = false;
        emit EnrollmentCommitmentRevoked(_commitment);
    }

    // -------------------------------------------------------
    // Voter Registration (ZKP-based)
    // -------------------------------------------------------

    /**
     * @notice Verify a student's eligibility using a zk-SNARK proof and register
     *         them as an eligible voter.
     *
     * @param _pA       Groth16 proof point A
     * @param _pB       Groth16 proof point B
     * @param _pC       Groth16 proof point C
     * @param _pubSignals Public signals: [enrollmentCommitment, nullifierHash, electionId, ephemeralDid]
     *
     * @dev The proof demonstrates:
     *   1. The prover knows (matricNumber, departmentId, enrollmentSecret) whose
     *      Poseidon hash equals the public enrollmentCommitment.
     *   2. The nullifierHash is correctly derived from (matricNumber, electionId).
     */
    function verifyAndRegister(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[4] calldata _pubSignals
    ) external {
        // Extract public signals
        bytes32 enrollmentCommitment = bytes32(_pubSignals[0]);
        bytes32 nullifierHash = bytes32(_pubSignals[1]);
        uint256 electionId = _pubSignals[2];
        bytes32 ephemeralDid = bytes32(_pubSignals[3]);

        // Validate election context
        require(electionId == currentElectionId, "VoterEligibility: wrong election ID");

        // Validate enrollment commitment is registered
        require(
            enrollmentCommitments[enrollmentCommitment],
            "VoterEligibility: unknown enrollment commitment"
        );

        // Prevent double registration using nullifier
        require(!usedNullifiers[nullifierHash], "VoterEligibility: already registered");

        // Prevent re-registration of the same DID for this election
        require(!eligibleVoters[electionId][ephemeralDid], "VoterEligibility: DID already eligible");

        // Verify the zk-SNARK proof on-chain
        bool proofValid = verifier.verifyProof(_pA, _pB, _pC, _pubSignals);
        require(proofValid, "VoterEligibility: invalid proof");

        // Mark nullifier as used and DID as eligible for this election
        // Register the Ephemeral DID as an eligible voter for this election
        usedNullifiers[nullifierHash] = true;
        eligibleVoters[electionId][ephemeralDid] = true;
        eligibleVoterCount++;

        emit VoterVerified(ephemeralDid, nullifierHash);
    }

    // -------------------------------------------------------
    // View Functions
    // -------------------------------------------------------

    /**
     * @notice Check if a DID is eligible to vote in a specific election
     * @param _electionId ID of the election
     * @param _didHash Hash of the DID to check
     * @return True if the DID is registered as eligible
     */
    function isEligible(uint256 _electionId, bytes32 _didHash) external view returns (bool) {
        return eligibleVoters[_electionId][_didHash];
    }
}
