/**
 * Deployment Script
 *
 * Deploys the complete voting system to a Hardhat local network:
 * 1. Verifier.sol (auto-generated Groth16 verifier)
 * 2. VoterEligibility.sol
 * 3. Voting.sol
 * 4. SmartAccountFactory
 * 5. VotingPaymaster
 *
 * Then initializes the election with test candidates and enrollment commitments.
 */

const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [admin] = await ethers.getSigners();
  console.log("Deploying contracts with admin:", admin.address);
  console.log("Admin balance:", ethers.formatEther(await ethers.provider.getBalance(admin.address)), "ETH\n");

  // -------------------------------------------------------
  // 1. Deploy Groth16 Verifier
  // -------------------------------------------------------
  console.log("[1/5] Deploying Groth16 Verifier...");

  // Check if Verifier.sol exists (generated by setup-zkp.js)
  const verifierPath = path.join(__dirname, "../contracts/Verifier.sol");
  if (!fs.existsSync(verifierPath)) {
    console.error("Error: Verifier.sol not found. Run 'node scripts/setup-zkp.js' first.");
    process.exit(1);
  }

  const Verifier = await ethers.getContractFactory("Groth16Verifier");
  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();
  const verifierAddr = await verifier.getAddress();
  console.log("   ✓ Verifier deployed at:", verifierAddr);

  // -------------------------------------------------------
  // 2. Deploy VoterEligibility
  // -------------------------------------------------------
  console.log("[2/5] Deploying VoterEligibility...");
  const VoterEligibility = await ethers.getContractFactory("VoterEligibility");
  const eligibility = await VoterEligibility.deploy(verifierAddr);
  await eligibility.waitForDeployment();
  const eligibilityAddr = await eligibility.getAddress();
  console.log("   ✓ VoterEligibility deployed at:", eligibilityAddr);

  // -------------------------------------------------------
  // 3. Deploy Voting
  // -------------------------------------------------------
  console.log("[3/5] Deploying Voting...");
  const VotingContract = await ethers.getContractFactory("Voting");
  const voting = await VotingContract.deploy(eligibilityAddr);
  await voting.waitForDeployment();
  const votingAddr = await voting.getAddress();
  console.log("   ✓ Voting deployed at:", votingAddr);

  // -------------------------------------------------------
  // 4. Deploy SmartAccountFactory
  // -------------------------------------------------------
  console.log("[4/5] Deploying SmartAccountFactory...");
  const SmartAccountFactory = await ethers.getContractFactory("SmartAccountFactory");
  const factory = await SmartAccountFactory.deploy();
  await factory.waitForDeployment();
  const factoryAddr = await factory.getAddress();
  console.log("   ✓ SmartAccountFactory deployed at:", factoryAddr);

  // -------------------------------------------------------
  // 5. Deploy VotingPaymaster
  // -------------------------------------------------------
  console.log("[5/5] Deploying VotingPaymaster...");
  // For the prototype, the admin address serves as a simplified EntryPoint
  const VotingPaymaster = await ethers.getContractFactory("VotingPaymaster");
  const paymaster = await VotingPaymaster.deploy(admin.address, votingAddr);
  await paymaster.waitForDeployment();
  const paymasterAddr = await paymaster.getAddress();
  console.log("   ✓ VotingPaymaster deployed at:", paymasterAddr);

  // -------------------------------------------------------
  // Initialize Election
  // -------------------------------------------------------
  console.log("\n--- Initializing Election ---");

  // Create election in eligibility contract
  const electionId = 1;
  await eligibility.createElection(electionId);
  console.log("   ✓ Election created with ID:", electionId);

  // Initialize election in voting contract
  const now = Math.floor(Date.now() / 1000);
  const startTime = now;
  const endTime = now + 86400; // 24 hours
  await voting.initializeElection(electionId, startTime, endTime);
  console.log("   ✓ Election initialized (24h window)");

  // Add candidates
  const candidates = [
    { id: 1, name: "Adewale Johnson", party: "Progressive Students Alliance" },
    { id: 2, name: "Chioma Okafor", party: "Students United Front" },
    { id: 3, name: "Emeka Nwosu", party: "Academic Excellence Movement" },
  ];

  for (const c of candidates) {
    await voting.addCandidate(c.id, c.name, c.party);
    console.log(`   ✓ Candidate added: ${c.name} (${c.party})`);
  }

  // -------------------------------------------------------
  // Save deployment addresses
  // -------------------------------------------------------
  const deployment = {
    network: "localhost",
    chainId: 1337,
    admin: admin.address,
    contracts: {
      Verifier: verifierAddr,
      VoterEligibility: eligibilityAddr,
      Voting: votingAddr,
      SmartAccountFactory: factoryAddr,
      VotingPaymaster: paymasterAddr,
    },
    election: {
      id: electionId,
      startTime,
      endTime,
      candidates,
    },
    deployedAt: new Date().toISOString(),
  };

  const deploymentPath = path.join(__dirname, "../deployment.json");
  fs.writeFileSync(deploymentPath, JSON.stringify(deployment, null, 2));
  console.log(`\n✓ Deployment addresses saved to ${deploymentPath}`);
  console.log("\n=== Deployment Complete ===");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
