/**
 * Deployment Script
 *
 * Deploys the complete voting system to a Hardhat local network:
 * 1. Verifier.sol (auto-generated Groth16 verifier)
 * 2. VoterEligibility.sol
 * 3. Voting.sol
 * 4. SmartAccountFactory
 * 5. VotingPaymaster
 *
 * Then initializes the election with test candidates and enrollment commitments.
 */

const { ethers, network } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [admin] = await ethers.getSigners();
  console.log("Deploying contracts with admin:", admin.address);
  console.log("Admin balance:", ethers.formatEther(await ethers.provider.getBalance(admin.address)), "ETH\n");

  // -------------------------------------------------------
  // 1. Deploy Groth16 Verifier
  // -------------------------------------------------------
  console.log("[1/5] Deploying Groth16 Verifier...");

  // Check if Verifier.sol exists (generated by setup-zkp.js)
  const verifierPath = path.join(__dirname, "../contracts/Verifier.sol");
  if (!fs.existsSync(verifierPath)) {
    console.error("Error: Verifier.sol not found. Run 'node scripts/setup-zkp.js' first.");
    process.exit(1);
  }

  const Verifier = await ethers.getContractFactory("Groth16Verifier");
  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();
  const verifierAddr = await verifier.getAddress();
  console.log("   ✓ Verifier deployed at:", verifierAddr);

  // -------------------------------------------------------
  // 2. Deploy VoterEligibility
  // -------------------------------------------------------
  console.log("[2/5] Deploying VoterEligibility...");
  const VoterEligibility = await ethers.getContractFactory("VoterEligibility");
  const eligibility = await VoterEligibility.deploy(verifierAddr);
  await eligibility.waitForDeployment();
  const eligibilityAddr = await eligibility.getAddress();
  console.log("   ✓ VoterEligibility deployed at:", eligibilityAddr);

  // -------------------------------------------------------
  // 3. Deploy Voting
  // -------------------------------------------------------
  console.log("[3/5] Deploying Voting...");
  const VotingContract = await ethers.getContractFactory("Voting");
  const voting = await VotingContract.deploy(eligibilityAddr);
  await voting.waitForDeployment();
  const votingAddr = await voting.getAddress();
  console.log("   ✓ Voting deployed at:", votingAddr);

  // -------------------------------------------------------
  // 4. Deploy SmartAccountFactory
  // -------------------------------------------------------
  console.log("[4/5] Deploying SmartAccountFactory...");
  const SmartAccountFactory = await ethers.getContractFactory("SmartAccountFactory");
  const factory = await SmartAccountFactory.deploy();
  await factory.waitForDeployment();
  const factoryAddr = await factory.getAddress();
  console.log("   ✓ SmartAccountFactory deployed at:", factoryAddr);

  // -------------------------------------------------------
  // 5. Deploy VotingPaymaster
  // -------------------------------------------------------
  console.log("[5/5] Deploying VotingPaymaster...");
  // For the prototype, the admin address serves as a simplified EntryPoint
  const VotingPaymaster = await ethers.getContractFactory("VotingPaymaster");
  const paymaster = await VotingPaymaster.deploy(admin.address, votingAddr);
  await paymaster.waitForDeployment();
  const paymasterAddr = await paymaster.getAddress();
  console.log("   ✓ VotingPaymaster deployed at:", paymasterAddr);

  // -------------------------------------------------------
  // Save deployment addresses (Blank Election State)
  // -------------------------------------------------------
  const deployment = {
    network: network.name,
    chainId: network.config.chainId || (network.name === "sepolia" ? 11155111 : 1337),
    admin: admin.address,
    contracts: {
      Verifier: verifierAddr,
      VoterEligibility: eligibilityAddr,
      Voting: votingAddr,
      SmartAccountFactory: factoryAddr,
      VotingPaymaster: paymasterAddr,
    },
    election: {
      id: 0,
      startTime: 0,
      endTime: 0,
      candidates: [],
    },
    deployedAt: new Date().toISOString(),
  };

  const deploymentPath = path.join(__dirname, "../deployment.json");
  const frontendDeploymentPath = path.join(__dirname, "../frontend/src/config/deployment.json");
  
  fs.writeFileSync(deploymentPath, JSON.stringify(deployment, null, 2));
  fs.writeFileSync(frontendDeploymentPath, JSON.stringify(deployment, null, 2));
  
  console.log(`\n✓ Deployment addresses saved to ${deploymentPath}`);
  console.log(`✓ Deployment addresses synced to ${frontendDeploymentPath}`);
  console.log("\n=== Deployment Complete ===");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
